# Generated by Django 4.0.6 on 2022-07-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100, verbose_name='Филиал')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('birth', models.CharField(max_length=20, verbose_name='Дата рождения')),
                ('comedate', models.CharField(max_length=20, verbose_name='Дата приема на работу')),
                ('salary', models.FloatField(max_length=100, verbose_name='Зарплата')),
            ],
        ),
    ]
